### ISSUE TITLE
Methods in FileFormatLister are a little long and have less readability

### ISSUE THREAD

**Issue by jerryjohnjacob** [akshaybhalotia/RubyEx1#1]
The methods in the FileFormatLister class are rather long and seem a little difficult to follow. The code organization is hampering the readability. Also, the use of switch cases and multiple conditionals is making the flow of control tricky to follow.

Have a look at [this link](https://robots.thoughtbot.com/sandi-metz-rules-for-developers).

**Comment by akshaybhalotia** [comment]
I did some refactoring here. Please have a look.
