### ISSUE TITLE
The format loading mechanism kept outside the scope of any classes or methods

### ISSUE THREAD

**Issue by jerryjohnjacob** [akshaybhalotia/RubyEx1#3]
As a crucial part of the application, the code that loads up the formats does not seem to be in the best place possible given that it is just expected to get executed when the interpreter accesses the file.

**Comment by akshaybhalotia** [comment]
I did some refactoring here. Please have a look.

**Comment by jerryjohnjacob** [comment]
As a good practice, rather than just say that you did some refactoring, can you also make sure to describe the changes you have made as well?

**Comment by akshaybhalotia** [comment]
Sure, will take care of this.
